<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VersionPrefix>1.0.0</VersionPrefix>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;1591</NoWarn>
    <LangVersion>14</LangVersion>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Assembly.cs" />
    <Compile Include="SimsLoader\CobjReader.cs" />
    <Compile Include="SimsLoader\CompressionType.cs" />
    <Compile Include="SimsLoader\DbpfEntry.cs" />
    <Compile Include="SimsLoader\DbpfHeader.cs" />
    <Compile Include="SimsLoader\DbpfIndexReader.cs" />
    <Compile Include="SimsLoader\DbpfPackage.cs" />
    <Compile Include="SimsLoader\Examples.cs" />
    <Compile Include="SimsLoader\GeomReader.cs" />
    <Compile Include="SimsLoader\GeomStructures.cs" />
    <Compile Include="SimsLoader\PackageExtensions.cs" />
    <Compile Include="SimsLoader\RcolReader.cs" />
    <Compile Include="SimsLoader\ResourceKey.cs" />
    <Compile Include="SimsLoader\ResourceType.cs" />
    <Compile Include="SimsLoader\SpanReader.cs" />
    <Compile Include="SimsLoader\StblReader.cs" />
    <Compile Include="SimsMount.cs" />
    <Compile Include="Resource\ModelLoader.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Sandbox.Engine\Sandbox.Engine.csproj" />
    <ProjectReference Include="..\..\Sandbox.Filesystem\Sandbox.Filesystem.csproj" />
    <ProjectReference Include="..\..\Sandbox.System\Sandbox.System.csproj" />
    <ProjectReference Include="..\Sandbox.Mounting\Sandbox.Mounting.csproj" />
  </ItemGroup>

  <Target Name="CopyOutputDll" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFiles="..\..\..\game\mount\sims4\sims4.dll" />
  </Target>

</Project>
