using System.Text;

namespace Facepunch.Native;

/// <summary>
/// Writes the whole Linux build as one makefile. Every module is a phony target, objects carry compiler
/// generated header dependencies, and the default goal builds everything.
/// </summary>
public static class Makefile
{
	public static void Write( string name, List<Module> modules, Options options )
	{
		// The Linux makefile only carries Release; nothing ships a Linux debug build yet.
		const string config = "Release";
		var platform = (Linux64)NativePlatform.Current;
		var make = new StringBuilder();

		make.Append( "# Generated by SboxBuild. Edit src/**/*.build.cs, not this file.\n\n" );
		// make defines CXX and CC itself, so ?= would never take. Override make's own default and leave
		// anything coming from the environment or the command line alone.
		make.Append( $"ifeq ($(origin CXX),default)\n  CXX := {Linux64.Compiler}\nendif\n" );
		make.Append( $"ifeq ($(origin CC),default)\n  CC := {Linux64.CCompiler}\nendif\n" );
		make.Append( $"ifeq ($(origin AR),default)\n  AR := {Linux64.Archiver}\nendif\n" );
		make.Append( $"OBJCOPY ?= {Linux64.ObjCopy}\n" );
		make.Append( $"STRIP ?= {Linux64.Strip}\n" );
		make.Append( "MKDIR ?= mkdir -p\n\n" );
		make.Append( ".SUFFIXES:\n" );
		make.Append( ".PHONY: all clean force " + string.Join( ' ', modules.Select( m => m.Name ) ) + "\n" );
		// Named, not positional: the first rule in the file is not necessarily the one to build.
		make.Append( ".DEFAULT_GOAL := all\n\n" );
		make.Append( "all: " + string.Join( ' ', modules.Select( m => m.Name ) ) + "\n\n" );
		make.Append( "force:\n\n" );

		// The vendored SDL3 carries SONAME libSDL3.so.0, which is the name the loader then looks for, and
		// the tree only has the unversioned file.
		var sdl = $"{platform.SdlDir}/libSDL3.so";
		make.Append( $"{sdl}.0: {sdl}\n\tln -sf libSDL3.so $@\n\n" );

		// The schema compiler is a parent that shells out to a child, so a schema step waits for both.
		var schemaTools = modules
			.Where( m => m.Name is SchemaCompiler.ToolChild or SchemaCompiler.Tool )
			.Select( Output )
			.ToList();

		var depFiles = new List<string>();

		foreach ( var module in modules )
		{
			var settings = module.Configs.First( c => c.Name == config );
			var output = Output( module );
			var objDir = $"{module.Dir}/obj/{module.Name}/{config}/{Paths.Platform}";

			// An MSBuild macro would expand to nothing here, and a bare -I swallows the next argument.
			var includes = settings.Includes.Distinct().Where( i => !i.Contains( "$(" ) );

			var flags = string.Join( ' ', settings.Defines.Distinct().Select( d => $"-D{Escape( d )}" ) )
				+ " " + string.Join( ' ', includes.Select( i => $"-I{Path( i )}" ) )
				+ " " + string.Join( ' ', settings.Options.Distinct() );

			var upper = module.Name.ToUpperInvariant().Replace( '-', '_' );
			make.Append( $"# ---- {module.Name}\n" );
			make.Append( $"{upper}_FLAGS := {Collapse( flags )}\n" );

			// Objects depend on the flags, so editing a module definition rebuilds them. The file is only
			// touched when the flags actually differ, which is why it hangs off a phony target.
			var flagsFile = $"{objDir}/flags";
			make.Append( $"{flagsFile}: force\n" );
			make.Append( "\t@$(MKDIR) $(dir $@)\n" );
			make.Append( $"\t@echo '$({upper}_FLAGS)' | cmp -s - $@ || echo '$({upper}_FLAGS)' > $@\n" );

			// Generated code has to exist before anything compiles it.
			var schemaSentinel = Schema( make, module, config, objDir, schemaTools );
			var antlrStamp = Antlr( make, module, objDir );
			var generators = new[] { schemaSentinel, antlrStamp }.Where( s => s is not null ).ToList();

			var objects = new List<string>();

			foreach ( var file in module.ResolvedFiles )
			{
				if ( file.Kind != FileKind.Compile ) continue;
				if ( file.ExcludeFrom.Contains( config ) ) continue;

				var source = Path( file.Path );
				var obj = $"{objDir}/{System.IO.Path.GetFileNameWithoutExtension( file.Path )}_{Hash( file.Path )}.o";
				objects.Add( obj );
				depFiles.Add( obj + ".d" );

				// Everything is C++ unless it asked to be C, the same as MSVC's /TP on Windows. A module of C
				// sources still gets the standard .cpp sources every module gets, and those stay C++.
				bool asC = file.CompileAs == "CompileAsC"
					|| (module.CompileAsC && file.CompileAs is null && file.Path.EndsWith( ".c", StringComparison.OrdinalIgnoreCase ));
				var compiler = asC ? "$(CC)" : "$(CXX)";
				// The gnu dialect, because tier0's logging macros rely on the GNU handling of an empty
				// ##__VA_ARGS__. -fpermissive downgrades the conformance errors gcc raises and clang does not.
				// C++ only: gcc rejects -fpermissive for C.
				var extra = asC ? "" : " -x c++ -std=gnu++20 -fpermissive";
				var perFile = file.Clang.Count > 0 ? " " + string.Join( ' ', file.Clang ) : "";

				// Generated code reaches any source in the module, through a unity batch or a header, so every
				// object waits. Order only, so it does not force rebuilds.
				var order = generators.Count > 0 ? $" | {string.Join( ' ', generators )}" : "";

				make.Append( $"{obj}: {source} {flagsFile}{order}\n" );
				make.Append( $"\t@$(MKDIR) $(dir $@)\n" );
				make.Append( $"\t{compiler} $({upper}_FLAGS){extra}{perFile} -MMD -MF $@.d -c -o $@ $<\n" );
			}

			make.Append( $"{upper}_OBJS := {Collapse( string.Join( ' ', objects ) )}\n" );

			var dependencies = module.Dependencies
				.Where( modules.Contains )
				.Select( Output )
				.ToList();

			if ( module.Kind != ModuleKind.Lib ) dependencies.Add( $"{sdl}.0" );

			make.Append( $"{output}: $({upper}_OBJS) {string.Join( ' ', dependencies )}\n" );
			make.Append( $"\t@$(MKDIR) $(dir $@)\n" );

			if ( module.Kind == ModuleKind.Lib )
			{
				make.Append( $"\t$(AR) rcs $@ $({upper}_OBJS)\n" );
			}
			else
			{
				var libs = string.Join( ' ', settings.LinkLibs.Distinct().Select( l => $"-l{l}" ) );
				var dirs = string.Join( ' ', settings.LibDirs.Distinct().Select( d => $"-L{Path( d )}" ) );
				var inputs = module.Libraries.Select( l => LinkInput( l, modules ) ).Where( x => x is not null ).ToList();
				var linked = inputs.Count > 0
					? "-Wl,--start-group " + string.Join( ' ', inputs ) + " -Wl,--end-group"
					: "";

				var link = string.Join( ' ', settings.LinkOptions.Distinct().Select( Shell ) );

				make.Append( $"\t$(CXX) {link} -o $@ $({upper}_OBJS) {Collapse( linked )} {dirs} {libs}\n" );

				// Debug info moves out to the .dbg the debuglink points at, which the depot excludes. Every
				// configuration, so what ships is stripped whichever one built it.
				make.Append( "\t$(OBJCOPY) --only-keep-debug $@ $@.dbg\n" );
				make.Append( "\t$(OBJCOPY) --add-gnu-debuglink=$@.dbg $@\n" );
				make.Append( "\t$(STRIP) --strip-unneeded -x $@\n" );
			}

			make.Append( $"{module.Name}: {output}\n\n" );
		}

		var objDirs = depFiles.Select( d => System.IO.Path.GetDirectoryName( d ).Replace( '\\', '/' ) ).Distinct();
		make.Append( "clean:\n\trm -rf " + Collapse( string.Join( ' ', objDirs ) ) + "\n\n" );
		make.Append( "-include " + Collapse( string.Join( ' ', depFiles ) ) + "\n" );

		var path = System.IO.Path.Combine( Paths.SrcDir, $"{name}.mak" );
		var content = make.ToString();
		if ( File.Exists( path ) && File.ReadAllText( path ) == content ) return;

		File.WriteAllText( path, content, new UTF8Encoding( false ) );
	}

	/// <summary>
	/// The schema compiler writes one generated source per schematised header. Make cannot express a rule
	/// with several outputs, so the sentinel it writes is the real target and the sources hang off it.
	/// </summary>
	private static string Schema( StringBuilder make, Module module, string config, string objDir, List<string> tools )
	{
		if ( !module.Schema.Any ) return null;

		var sentinel = $"{objDir}/schema_sentinel.txt";
		var tool = $"{Paths.DevToolsDir}/{SchemaCompiler.Tool}";
		var info = SchemaCompiler.InfoPath( module );
		var inputs = string.Join( ' ', module.Schema.Files.Select( Path ) );

		var generated = module.ResolvedFiles
			.Where( f => f.Kind == FileKind.Compile && f.Path.Contains( SchemaCompiler.GeneratedRoot ) && !f.ExcludeFrom.Contains( config ) )
			.Select( f => Path( f.Path ) )
			.ToList();

		// Tools are order only: the step waits for one that is building, but a relink is not a reason to
		// regenerate.
		make.Append( $"{sentinel}: {Collapse( inputs )} {info} | {string.Join( ' ', tools )}\n" );
		make.Append( "\t@$(MKDIR) $(dir $@)\n" );
		make.Append( $"\t{tool} -schema_proj {info} -config {config.ToLowerInvariant()} -sentinel $@\n" );

		if ( generated.Count > 0 )
		{
			make.Append( $"{Collapse( string.Join( ' ', generated ) )}: {sentinel}\n" );
			make.Append( "\t@true\n" );
		}

		return sentinel;
	}

	/// <summary>One ANTLR run writes several files, so a stamp stands in as the target.</summary>
	private static string Antlr( StringBuilder make, Module module, string objDir )
	{
		if ( module.AntlrGrammars.Count == 0 ) return null;

		var stamp = $"{objDir}/antlr_stamp.txt";
		var tool = Paths.Relative( module.Dir, "devtools/bin/antlr3" ).Replace( '\\', '/' );
		var generated = new List<string>();

		var grammars = module.AntlrGrammars.Select( g => Paths.Resolve( module.Dir, g ) ).ToList();

		make.Append( $"{stamp}: {string.Join( ' ', grammars.Select( Path ) )}\n" );
		make.Append( "\t@$(MKDIR) $(dir $@)\n" );

		foreach ( var grammar in grammars )
		{
			// From the module directory, where the sources include the generated headers from. The input is
			// absolute because ANTLR mirrors a relative one's path under -o.
			make.Append( $"\tcd {Path( module.Dir )} && {tool} $(CURDIR)/{Path( grammar )} -o {AntlrOutput}\n" );

			var name = System.IO.Path.GetFileNameWithoutExtension( grammar );
			generated.Add( Path( $"{module.Dir}/{AntlrOutput}/{name}Lexer.c" ) );
			generated.Add( Path( $"{module.Dir}/{AntlrOutput}/{name}Parser.c" ) );
		}

		make.Append( "\t@touch $@\n" );
		make.Append( $"{Collapse( string.Join( ' ', generated ) )}: {stamp}\n" );
		make.Append( "\t@true\n" );

		return stamp;
	}

	private const string AntlrOutput = "generated_antlr_code";

	/// <summary>
	/// Static libraries are passed to the linker by path. There are no import libraries here, so another
	/// module's shared object is named with -l and found through its output directory.
	/// </summary>
	private static string LinkInput( string library, List<Module> modules )
	{
		var name = System.IO.Path.GetFileNameWithoutExtension( library );
		var dir = System.IO.Path.GetDirectoryName( library )?.Replace( '\\', '/' );
		if ( dir is null ) return null;

		// Another module in this build, whether or not it has been built yet.
		var target = modules.FirstOrDefault( m => m.OutputName == name );
		if ( target is not null )
			return target.Kind == ModuleKind.Lib
				? Output( target )
				: $"-l{target.OutputName}";

		// A prebuilt library sitting in a win64 folder means nothing here. A module that needs the Linux
		// build of it names that under if ( Linux ).
		if ( dir.Contains( "win64", StringComparison.OrdinalIgnoreCase ) ) return null;

		// Named in full, or with the prefix and extension left off.
		if ( library.EndsWith( ".a" ) || library.EndsWith( ".so" ) ) return Path( library );

		foreach ( var candidate in new[] { $"{dir}/lib{name}.a", $"{dir}/lib{name}.so" } )
			if ( File.Exists( System.IO.Path.Combine( Paths.SrcDir, candidate ) ) ) return candidate;

		// A prebuilt the Linux tree does not ship. Whatever needs it names its Linux build itself.
		return null;
	}

	private static string Path( string srcRelative ) => srcRelative.Replace( '\\', '/' );

	private static string Output( Module module ) =>
		$"{NativePlatform.Current.OutputDir( module )}/{NativePlatform.Current.OutputFile( module )}";

	private static string Escape( string define ) => define.Contains( ' ' ) ? $"\"{define}\"" : define;

	/// <summary>
	/// A literal $ (rpath's $ORIGIN) has to survive make, which wants $$, and then the shell, which wants
	/// it quoted.
	/// </summary>
	private static string Shell( string option ) => option.Contains( '$' ) ? $"'{option.Replace( "$", "$$" )}'" : option;

	/// <summary>Wrap a long value so the makefile stays readable.</summary>
	private static string Collapse( string value )
	{
		var parts = value.Split( ' ', StringSplitOptions.RemoveEmptyEntries );
		if ( parts.Length <= 6 ) return string.Join( ' ', parts );

		var lines = new List<string>();
		for ( int i = 0; i < parts.Length; i += 6 )
			lines.Add( string.Join( ' ', parts.Skip( i ).Take( 6 ) ) );

		return string.Join( " \\\n\t", lines );
	}

	/// <summary>Object files are flat, so sources with the same name need distinct object names.</summary>
	private static string Hash( string path )
	{
		uint hash = 2166136261;
		foreach ( var c in path ) hash = (hash ^ c) * 16777619;
		return hash.ToString( "x8" );
	}
}
