<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<VersionPrefix>1.0.0</VersionPrefix>
		<TargetFramework>net10.0</TargetFramework>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>fmod_mount</AssemblyName>
		<NoWarn>1701;1702;1591</NoWarn>
		<LangVersion>14</LangVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Sandbox.System\Sandbox.System.csproj" />
		<ProjectReference Include="..\Sandbox.Mounting\Sandbox.Mounting.csproj" />
	</ItemGroup>

	<Target Name="CopyOutputDll" AfterTargets="Build" Condition="'$(DeployMount)' != 'false'">
		<MakeDir Directories="..\..\..\game\mount\fmod_mount" />
		<Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFiles="..\..\..\game\mount\fmod_mount\fmod_mount.dll" />
	</Target>

</Project>
